Remove swift-driver from Windows builds
compnerd/swift-build pull request #277
Opened 2020-09-05 10:45 UTC by stevapple

Since swift-driver has no Windows implementations so far, remove it from Windows builds to avoid spoiling the toolchain.

2020-09-05 14:54 UTC, compnerd commented
You cannot remove the checkout step, it breaks the pipelines.

I dont understand the assertion that swift-driver doesnt have a windows implementation.  It absolutely does - otherwise you couldnt build/use swift-package-manager.

Could you please explain what the change is intended to do?

2020-09-05 14:56 UTC, compnerd requested changes
Sadly you cannot remove the checkout step, it breaks the pipelines :(

I dont understand the assertion that swift-driver doesnt have a windows implementation. It absolutely does - otherwise you couldnt build/use swift-package-manager.

Could you please explain what the change are intended to do?  Or where you intend to evolve them towards?

2020-09-08 15:26 UTC, compnerd commented
@stevapple - these are now required due to packaging swift-package-manager into the toolchain.  Is there anything that you hope to change here or should this be closed?

2020-09-08 23:58 UTC, stevapple commented
Nope. This PR is totally a mistake. I’ll close it now, sorry for troubling you.

2020-09-08 23:58 UTC, closed without merging

2020-09-09 00:45 UTC, compnerd commented
No worries, just wanted to make sure that if there was an issue we figured out what was happening.