WIX: allow user to customize install location
compnerd/swift-build pull request #309
Opened 2020-10-13 04:08 UTC by compnerd

2020-11-02 00:44 UTC, wjk requested changes
I recommend that you change the default `INSTALLDIR` value from `[WindowsVolume]` to `[WindowsVolume]\Library`. If users choose to install the Swift runtime into a different folder, chances are it will be a newly created, otherwise-empty folder. This way, there won't be an otherwise-useless Library folder inside that folder.

Note that if you choose to do this, you will have to get rid of all the `<Directory Id="LIBRARY" Name="Library">` tags in the MSI projects to match the change in the bundle project. (Everything inside those tags can be kept as-is. Just delete the lines containing the opening and closing tags for the Library directory element, then auto-reindent.)

2020-11-02 00:44 UTC, wjk commented on wix/windows-bundle.wxs
> +      Value="[WindowsVolume]"
```suggestion
      Value="[WindowsVolume]\Library"
```

2020-11-02 01:04 UTC, compnerd commented
Hmm, @wjk I think you have a good point.  However, I'm not convinced that should be part of this change.  Instead, we should make that change even if we don't actually manage to get this particular change merged because that actually improves the installer.

2020-11-02 01:42 UTC, wjk commented
So you're saying that we should change the INSTALLDIR in a later PR? Your message is kinda confusing.

2020-11-02 05:09 UTC, compnerd commented
I'm suggesting that we should do it in a different PR, but do that before this change.  I think that the change you are proposing will actually improve the installer for the extract only case and help with this PR.  Sorry about the message being confusing.

2022-12-29 03:31 UTC, compnerd commented
I'm going to close this for now.  This is pretty out of date, and more importantly, the installer content has moved to https://github.com/apple/swift-installer-scripts.

2022-12-29 03:31 UTC, closed without merging