WIX: enable Developer Mode with SwiftPM
compnerd/swift-build pull request #350
Opened 2021-02-19 17:07 UTC by stevapple

SwiftPM requires Developer Mode to function properly. Instead of asking users to enable it manually, we can enable it through the installer.

2021-02-19 17:09 UTC, stevapple commented
A brief explanation on what SwiftPM uses this for: SwiftPM needs Developer Mode to create symbolic links with the `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` flag (see [CreateSymbolicLinkW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw)), or it will throw an error on every successful build.

2021-02-19 22:08 UTC, compnerd requested changes
The fixes beyond the developer mode are good, can you split that out into a separate change?  The problem with the developer mode that I have is that it isn't entirely required.  I do not have developer mode enabled on my machine but am using swift package manager just fine.  I am uncomfortable with such a change.  I would rather that this be an explicit opt-in via a checkbox option in an advanced setting.

2021-02-20 02:15 UTC, stevapple commented
It’s really confusing though. May you check the key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock\AllowDevelopmentWithoutDevLicense` on your machine? If the value is 1, there should be other application that already enables it.

2021-02-20 17:19 UTC, compnerd commented
```
>reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock\AllowDevelopmentWithoutDevLicense
ERROR: The system was unable to find the specified registry key or value.
```

It is not confusing at all, it is well documented at https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw

2021-02-21 00:43 UTC, stevapple commented
According to the document and the implementation of `swift-corelibs-foundation` and `swift-package-manager`, there should always be a `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` flag passed to `CreateSymbolicLinkW`. If Developer Mode isn’t enabled, there should be error thrown. Did I miss any point?

2021-02-21 21:07 UTC, compnerd commented
`SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` does not mean that you can create the symbolic link without the privilege.  It means that the process does not need to be running in an elevated context.  You still need `SE_ALLOW_CREATE_SYMBOLIC_LINK_PRIVILEGE`.  Enabling Developer Mode will reduce the security on the system allowing untrusted code execution amongst other things.  One of the things it enables is effectively every process receiving that security permission, thus allowing the creation of symbolic links.

I've generally been very intentional about the Windows port.

2021-02-24 18:25 UTC, compnerd commented
Further verified: https://forums.swift.org/t/stochastic-errors-resolving-dependencies-and-or-building-with-feb-18-2021-snapshot

The developer mode is most definitely not the correct thing, and I don't think that is something that the installer should be doing by default.

2021-02-25 01:02 UTC, stevapple commented
In fact, I’ve already tried to alter user permission through WiX, and that seems impossible. There’s not even a way to grant that through the shell AFAIK.
Using Developer Mode is one of the solutions, and maybe the only one possible for an installer.

2021-02-25 01:10 UTC, stevapple commented
Another point is that there’s no `secpol.msc` on Windows 10 Home. Developer Mode  (by registry key), meanwhile, is available on all versions.

2021-02-25 15:39 UTC, compnerd commented
Application through a GPO should be possible to automate.  You should be able to create a C# Custom Action to apply the GPO.

2022-05-01 16:24 UTC, closed without merging