Disable sccache when building ICU for Android
compnerd/swift-build pull request #756
Opened 2024-07-01 18:10 UTC by kendalharland

These jobs are hitting a known fatal error in sccache where files aren't removed from the cache

2024-07-01 18:31 UTC, compnerd requested changes
Please inline the error message in the commit message so that we can follow what is going on, the logs are inaccessible due to the corporate security and broken Arc.

2024-07-01 20:14 UTC, kendalharland commented
> Please inline the error message in the commit message so that we can follow what is going on, the logs are inaccessible due to the corporate security and broken Arc.

Done

2024-07-01 21:30 UTC, compnerd commented
Hmm, its unclear if this is really the right approach - it just seems like you have a corrupted cache? What happens if you clear out the cache?

2024-07-01 21:41 UTC, kendalharland commented
> Hmm, its unclear if this is really the right approach - it just seems like you have a corrupted cache? What happens if you clear out the cache?

I don't think clearing the cache will fix things, given that this is flaking on both GitHub and Azure images where each Android ICU job executes in  a fresh VM instance. It seems like a bug in sccache that surfaces with higher probably when building for Android, so disabling it just unbreaks the build for the time being.

That being said, how does one clear the cache used by sccache? Where in the workflow could we do this if we wanted to workaround the error when building ICU?

2024-07-01 21:43 UTC, compnerd commented
You are missing the point of sccache ;-). The entire point is that the content *is* cached, even on a fresh VM image. You should look at the caches for the job, clearing out all the old runs should hopefully fix the issue.

2024-07-01 22:01 UTC, kendalharland commented
Ah, I see what you mean.  I just deleted each of the android ICU caches and will see if that works.

2024-07-01 22:25 UTC, kendalharland commented
That did it, thanks for the tip!

2024-07-08 16:37 UTC, kendalharland commented
Reopening because the sccache corruption comes back each time we attempt to target Android when building ICU, and it's not immediately clear what is causing this. We'll need to disable this while we debug.

2024-07-08 17:12 UTC, hjyamauchi approved these changes

2024-07-08 21:53 UTC, kendalharland commented
I'll need @compnerd to merge since I don't have write access

2024-07-08 22:05 UTC, compnerd reviewed
I do think that taking a closer look to the change is valuable - I'm concerned that this will remain disabled indefinitely.

2024-07-08 22:05 UTC, compnerd commented on .github/workflows/swift-toolchain.yml
> +                -D CMAKE_C_COMPILER_LAUNCHER=${{ matrix.os == 'Windows' && 'sccache' || '' }} `
Why is this change needed with the condition above?

2024-07-09 16:51 UTC, kendalharland commented
This is not needed after https://github.com/compnerd/swift-build/pull/757.  The reason for the cache misses is that the cache size was too small to begin with, so the first cache we create when building Android for ICU does not contain all of the expected entries causing sccache to subsequently fail when purging existing entries to make space

2024-07-09 16:51 UTC, closed without merging