Modify GitHub conditionals to compare strings
compnerd/swift-build pull request #818
Opened 2024-08-27 00:22 UTC by Steelskin

A raw input of "false" as a string does not expand to a false boolean value.

2024-08-27 00:40 UTC, compnerd requested changes
Please change the type of the input itself. They are currently incorrectly marked as `string` rather than `boolean`.

2024-08-27 17:17 UTC, Steelskin commented
> Please change the type of the input itself. They are currently incorrectly marked as `string` rather than `boolean`.

This is done, I had to modify the way we pass the variable but it works now (verified on downstream CI)

2024-08-27 19:22 UTC, hjyamauchi approved these changes

2024-08-31 00:55 UTC, compnerd approved these changes

2024-08-31 00:55 UTC, merged